### ISSUE TITLE
Small change in SS01

### ISSUE THREAD

**Issue by VladWinner** [hyvyys/Tektur#1]
Hello! I think that existing stylistic set can be improved.
### SS01: Round A
![image](https://user-images.githubusercontent.com/13555921/123546595-ee066f80-d765-11eb-92db-c096c31f7eac.png)
Rule should also be applied to letter "А" `U+0410` 
like "C" `U+0043`→"С"`U+0421` in SS03 
or "M"`U+004D`→"М"`U+041C` in SS04

**Comment by hyvyys** [comment]
Hi! Thanks for bringing this up. I added an alternate for Cyrillic A to ss01.

Fixed by a5dc1a3
