### ISSUE TITLE
Geometry refinements

### ISSUE THREAD

**Issue by VladWinner** [hyvyys/Tektur#2]
### 1) Wrong uppercase K with hook — "Ƙ" `U+0198`
![image](https://user-images.githubusercontent.com/13555921/123559787-e1eed200-d7a6-11eb-8860-1cca3fc46e38.png)
[Issue post from another font (with screenshot extracted from Unicode chart PDF)](https://github.com/be5invis/Iosevka/issues/1123#issuecomment-862019080)
[Wikipedia](https://en.wikipedia.org/wiki/Ƙ)

### 2) Greek small letter Eta mistakenly looks the same as Latin "n" — "η" `U+03B7`, "ή" `U+03AE`
![image](https://user-images.githubusercontent.com/13555921/123559735-8e7c8400-d7a6-11eb-85e4-d29d499865cb.png)

### 3) Greek small letter Phi looks the same as Cyrillic "ф" — "φ" `U+03C6`
![image](https://user-images.githubusercontent.com/13555921/123560745-d69ea500-d7ac-11eb-88ac-cf6ff93077a2.png)

### 4) Greek small letter Chi mistakenly looks the same as Latin "x" or Cyrillic "х" — "χ" `U+03C7`
Latin "x", Cyrillic "х" and Greek "χ":
![image](https://user-images.githubusercontent.com/13555921/123560881-b6bbb100-d7ad-11eb-9624-c5463d0ecadd.png)

### 5) Unnecessary upper serif in Cyrillic "л" (does not match with design of rest Cyrillic letters) — "л" `U+043B`
Also, usually "л" `U+043B` and "Д" `U+0414` have a similar upper part with right angle connection on the left (but it's hard for me to say how to adhere this in current stylized font)
![image](https://user-images.githubusercontent.com/13555921/123561770-0650ab80-d7b3-11eb-896c-f349fe182a57.png)

**Comment by VladWinner** [comment]
Then I don't think you need to change anything in cases of intentional stylistic decisions. I myself do not use the Greek language, it was just strange for me as a Cyrillic user to see such a solution after a dozen fonts viewed. I like new "open phi" visually more than current, but all of this is subjective. 

I also think your new variant for `л` from screenshot is very tasty. Yes, leave the foot in same place, it really looks as it should.

**Comment by hyvyys** [comment]
@VladWinner Thank you.
