### ISSUE TITLE
Google Fonts version or v.1.005, e.g.?

### ISSUE THREAD

**Issue by Twilightssuperb** [hyvyys/Tektur#5]
Will Google Fonts version be different form this v.1.004 release? GF [issue](https://github.com/google/fonts/issues/2964) and discussion there says yes. Will you update this release?

Sorry for the dumb question. :)

**Comment by hyvyys** [comment]
Yes, it will differ. I forgot to bump the version number in the midst of those changes. @RosaWagner if I bump the version number now, can you pass that upstream?

**Comment by RosaWagner** [comment]
Yes next week

**Comment by Twilightssuperb** [comment]
@hyvyys, please, publish v.1.005 release.

**Comment by hyvyys** [comment]
@Twilightssuperb The fonts can be downloaded from the Code tab (green Code button -> Download ZIP). I will wait with publishing a GitHub release for now as I have some unresolved doubts about the recent changes and whether more changes would be required. For now this is what has changed from 1.004:

* Change vertical metrics: desc -250 => desc -300
* Fix localization for BGR (missing el-cy)
* Add localization for SRB
* Update sidebearings, remove anchors in spacing accents

**Comment by Twilightssuperb** [comment]
Thx for explanation. I should wait for further changes.

**Comment by hyvyys** [comment]
https://github.com/hyvyys/Tektur/releases/tag/v1.005
